# Generated by Django 4.2.4 on 2023-10-17 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_article_tags_alter_scope_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopess', to='articles.tag', verbose_name='раздел'),
        ),
    ]
